// src/vue/App.vue
<template lang="pug">
  .container 
    h2 Vue!
    h2 Let's count! {{counter}}
    ul
      li
        a(href='/index.html') Home
      li
        a(href='/react.html') go to React app!
</template>

<script lang="ts">
import Vue from "vue";

let counter: string;
counter = 0;

export default Vue.extend({
  data() {
    return {
      counter,
    };
  },
  mounted() {
    setInterval(() => {
      this.counter++;
    }, 1000);
  },
});
</script>

<style lang="stylus" scoped>
bgStyle = darkslategray
textStyle = aquamarine

.container
  display: flex
  align-items: center
  justify-content: center
  flex-direction: column
  width: 900px
  padding: 40px
  font-family: sans-serif
  background-color: bgStyle
  color: textStyle

  h2
    font-size: 64px

  a
    font-size: 28px
    color: mintcream
</style>

// src/react/App.jsx
import React, { useState } from "react";
import swcLogo from "../images/swc-logo.svg";
import styled from "styled-components";

const Container = styled.div`
  display: flex;
  flex-direction: column;
  place-items: center;

  background-color: midnightblue;
  color: cornflowerblue;
  font-family: sans-serif;
  width: 900px;
  padding: 40px;

  h2 {
    font-size: 64px;
  }

  a {
    font-size: 28px;
    color: aliceblue;
  }
`;

const App = () => {
  const [state, setState] = useState(false);

  return (
    <Container>
      <h2 onClick={() => setState(!state)}>
        What is state?: {state.toString()}
      </h2>

      <a href="/index.html">Home</a>
      <a href="/vue.html">Go to the Vue app</a>
      <img src={swcLogo} alt="" width="800" />
    </Container>
  );
};

export default App;
